# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get next number for PK generation
#' In a vector of numbers, the function finds out the first missing number and returns it.
#' If it does not find any missing value, it return number next to the last number.
#' @param x vector of numbers.
nextNumber <- function(x) {
    .Call('dbfrontendR_nextNumber', PACKAGE = 'dbfrontendR', x)
}

